# Generated by Django 3.1 on 2022-04-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20220418_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzeria',
            old_name='pizzeria',
            new_name='pizzeria_name',
        ),
    ]
